export default [
  // first 20 photos for advanced
  {title: '1', src: "/assets/gallery/1.jpg", tags: ["woman"]},
  {title: '2', src: "/assets/gallery/2.jpg", tags: ["cow"]},
  {title: '3', src: "/assets/gallery/3.jpg", tags: ["forest"]},
  {title: '4', src: "/assets/gallery/4.jpg", tags: ["laptop", "apple", "macbook"]},
  {title: '5', src: "/assets/gallery/5.jpg", tags: ["book"]},
  {title: '6', src: "/assets/gallery/6.jpg", tags: ["man"]},
  {title: '7', src: "/assets/gallery/7.jpg", tags: ["style", "watch", "suite", "man"]},
  {title: '8', src: "/assets/gallery/8.jpg", tags: ["shows"]},
  {title: '9', src: "/assets/gallery/9.jpg", tags: ["shows"]},
  {title: '10', src: "/assets/gallery/10.jpg", tags: ["class", "class room", "lecture", "school"]},
  {title: '11', src: "/assets/gallery/11.jpg", tags: ["blonde", "woman", "theatre", "beautiful"]},
  {title: '12', src: "/assets/gallery/12.jpg", tags: ["books"]},
  {title: '13', src: "/assets/gallery/13.jpg", tags: ["beach", "la", "men"]},
  {title: '14', src: "/assets/gallery/14.jpg", tags: ["forest", "red", "beautiful"]},
  {title: '15', src: "/assets/gallery/15.jpg", tags: ["forest"]},
  {title: '16', src: "/assets/gallery/16.jpg", tags: ["apples"]},
  {title: '17', src: "/assets/gallery/17.jpg", tags: ["wine"]},
  {title: '18', src: "/assets/gallery/18.jpg", tags: ["road", "highway"]},
  {title: '19', src: "/assets/gallery/19.jpg", tags: ["style", "vest", "man"]},
  {title: '20', src: "/assets/gallery/20.jpg", tags: ["style", "vest", "man"]},

  // next 20 photos for advanced
  {title: '21', src: "/assets/gallery/21.jpg", tags: ["watch", "man", "style"]},
  {title: '22', src: "/assets/gallery/22.jpg", tags: ["blonde", "woman", "beautiful"]},
  {title: '23', src: "/assets/gallery/23.jpg", tags: ["blonde", "woman", "beautiful"]},
  {title: '24', src: "/assets/gallery/24.jpg", tags: [""]},
  {title: '25', src: "/assets/gallery/25.jpg", tags: [""]},
  {title: '26', src: "/assets/gallery/26.jpg", tags: [""]},
  {title: '27', src: "/assets/gallery/27.jpg", tags: [""]},
  {title: '28', src: "/assets/gallery/28.jpg", tags: [""]},
  {title: '29', src: "/assets/gallery/29.jpg", tags: [""]},
  {title: '30', src: "/assets/gallery/30.jpg", tags: [""]},
  {title: '31', src: "/assets/gallery/31.jpg", tags: [""]},
  {title: '32', src: "/assets/gallery/32.jpg", tags: [""]},
  {title: '33', src: "/assets/gallery/33.jpg", tags: [""]},
  {title: '34', src: "/assets/gallery/34.jpg", tags: [""]},
  {title: '35', src: "/assets/gallery/35.jpg", tags: [""]},
  {title: '36', src: "/assets/gallery/36.jpg", tags: [""]},
  {title: '37', src: "/assets/gallery/37.jpg", tags: [""]},
  {title: '38', src: "/assets/gallery/38.jpg", tags: [""]},
  {title: '39', src: "/assets/gallery/39.jpg", tags: [""]},

  // next 20 photos for advanced
  {title: '40', src: "/assets/gallery/40.jpg", tags: [""]},
  {title: '41', src: "/assets/gallery/41.jpg", tags: [""]},
  {title: '42', src: "/assets/gallery/42.jpg", tags: [""]},
  {title: '43', src: "/assets/gallery/43.jpg", tags: [""]},
  {title: '44', src: "/assets/gallery/44.jpg", tags: [""]},
  {title: '45', src: "/assets/gallery/45.jpg", tags: [""]},
  {title: '46', src: "/assets/gallery/46.jpg", tags: [""]},
  {title: '47', src: "/assets/gallery/47.jpg", tags: [""]},
  {title: '48', src: "/assets/gallery/48.jpg", tags: [""]},
  {title: '49', src: "/assets/gallery/49.jpg", tags: [""]},
  {title: '50', src: "/assets/gallery/50.jpg", tags: [""]},
  {title: '51', src: "/assets/gallery/51.jpg", tags: [""]},
  {title: '52', src: "/assets/gallery/52.jpg", tags: [""]},
  {title: '53', src: "/assets/gallery/53.jpg", tags: [""]},
  {title: '54', src: "/assets/gallery/54.jpg", tags: [""]},
  {title: '55', src: "/assets/gallery/55.jpg", tags: [""]},
  {title: '56', src: "/assets/gallery/56.jpg", tags: [""]},
  {title: '57', src: "/assets/gallery/57.jpg", tags: [""]},
  {title: '58', src: "/assets/gallery/58.jpg", tags: [""]},
  {title: '59', src: "/assets/gallery/59.jpg", tags: [""]},
  {title: '60', src: "/assets/gallery/60.jpg", tags: [""]},

  // next 5 photos for routing
  {title: '61', src: "/assets/design-images/nature-1.jpg", tags: [""]},
  {title: '62', src: "/assets/design-images/people-2.jpg", tags: [""]},
  {title: '63', src: "/assets/design-images/dinner-3.jpg", tags: [""]},
  {title: '64', src: "/assets/design-images/space-1.jpg", tags: [""]},
  {title: '65', src: "/assets/design-images/outside-1.jpg", tags: [""]},
];
