export default [
  // first 20 photos for advanced
  {title: '1', src: "/assets/gallery/1.jpg", tags: ["woman"]},
  {title: '2', src: "/assets/gallery/2.jpg", tags: ["cow", "animal"]},
  {title: '3', src: "/assets/gallery/3.jpg", tags: ["forest", "nature"]},
  {title: '4', src: "/assets/gallery/4.jpg", tags: ["laptop", "apple", "macbook"]},
  {title: '5', src: "/assets/gallery/5.jpg", tags: ["book", "write", "reading"]},
  {title: '6', src: "/assets/gallery/6.jpg", tags: ["man", "cool"]},
  {title: '7', src: "/assets/gallery/7.jpg", tags: ["style", "watch", "suite", "man"]},
  {title: '8', src: "/assets/gallery/8.jpg", tags: ["shoes", "style"]},
  {title: '9', src: "/assets/gallery/9.jpg", tags: ["woman", "class", "style"]},
  {title: '10', src: "/assets/gallery/10.jpg", tags: ["class", "class room", "lecture", "school"]},
  {title: '11', src: "/assets/gallery/11.jpg", tags: ["blonde", "woman", "theatre", "beautiful"]},
  {title: '12', src: "/assets/gallery/12.jpg", tags: ["books", "reading", "writing"]},
  {title: '13', src: "/assets/gallery/13.jpg", tags: ["beach", "la", "men"]},
  {title: '14', src: "/assets/gallery/14.jpg", tags: ["forest", "red", "beautiful"]},
  {title: '15', src: "/assets/gallery/15.jpg", tags: ["forest", "green"]},
  {title: '16', src: "/assets/gallery/16.jpg", tags: ["apples", "food"]},
  {title: '17', src: "/assets/gallery/17.jpg", tags: ["wine", "food"]},
  {title: '18', src: "/assets/gallery/18.jpg", tags: ["road", "highway"]},
  {title: '19', src: "/assets/gallery/19.jpg", tags: ["style", "vest", "man"]},
  {title: '20', src: "/assets/gallery/20.jpg", tags: ["style", "tie", "clothing"]},

  // next 20 photos for advanced
  {title: '21', src: "/assets/gallery/21.jpg", tags: ["watch", "man", "style"]},
  {title: '22', src: "/assets/gallery/22.jpg", tags: ["blonde", "woman", "beautiful"]},
  {title: '23', src: "/assets/gallery/23.jpg", tags: ["woman", "beautiful"]},
  {title: '24', src: "/assets/gallery/24.jpg", tags: ["london", "city"]},
  {title: '25', src: "/assets/gallery/25.jpg", tags: ["life", "friends", "bond"]},
  {title: '26', src: "/assets/gallery/26.jpg", tags: ["city", "zurich"]},
  {title: '27', src: "/assets/gallery/27.jpg", tags: ["skateboard", "cool"]},
  {title: '28', src: "/assets/gallery/28.jpg", tags: ["skateboard", "cool"]},
  {title: '29', src: "/assets/gallery/29.jpg", tags: ["building", "city"]},
  {title: '30', src: "/assets/gallery/30.jpg", tags: ["train", "travel"]},
  {title: '31', src: "/assets/gallery/31.jpg", tags: ["amsterdam", "city"]},
  {title: '32', src: "/assets/gallery/32.jpg", tags: ["amsterdam", "alley", "city"]},
  {title: '33', src: "/assets/gallery/33.jpg", tags: ["new york", "arc", "city"]},
  {title: '34', src: "/assets/gallery/34.jpg", tags: ["new york", "city", "building"]},
  {title: '35', src: "/assets/gallery/35.jpg", tags: ["tower", "city", "building", "tower"]},
  {title: '36', src: "/assets/gallery/36.jpg", tags: ["france", "paris", "tower"]},
  {title: '37', src: "/assets/gallery/37.jpg", tags: ["amsterdam", "river"]},
  {title: '38', src: "/assets/gallery/38.jpg", tags: ["laptop", "code", "programming"]},
  {title: '39', src: "/assets/gallery/39.jpg", tags: ["motorcycle", "travel"]},
  {title: '40', src: "/assets/gallery/40.jpg", tags: ["guitar", "music"]},

  // next 20 photos for advanced
  {title: '41', src: "/assets/gallery/41.jpg", tags: ["cellphone", "iphone", "apple"]},
  {title: '42', src: "/assets/gallery/42.jpg", tags: ["forest", "snow", "nature"]},
  {title: '43', src: "/assets/gallery/43.jpg", tags: ["iphone", "apple", "cellphone", "apps"]},
  {title: '44', src: "/assets/gallery/44.jpg", tags: ["drawing", "art", "paper"]},
  {title: '45', src: "/assets/gallery/45.jpg", tags: ["bike", "art", "street"]},
  {title: '46', src: "/assets/gallery/46.jpg", tags: ["colors"]},
  {title: '47', src: "/assets/gallery/47.jpg", tags: ["paper", "drawing", "art"]},
  {title: '48', src: "/assets/gallery/48.jpg", tags: ["music", "headphones"]},
  {title: '49', src: "/assets/gallery/49.jpg", tags: ["music", "vinyl", "record"]},
  {title: '50', src: "/assets/gallery/50.jpg", tags: ["music", "elvis"]},
  {title: '51', src: "/assets/gallery/51.jpg", tags: ["music", "speaker"]},
  {title: '52', src: "/assets/gallery/52.jpg", tags: ["vinyl", "record", "player"]},
  {title: '53', src: "/assets/gallery/53.jpg", tags: ["nature", "green"]},
  {title: '54', src: "/assets/gallery/54.jpg", tags: ["leaves", "nature"]},
  {title: '55', src: "/assets/gallery/55.jpg", tags: ["grass", "outside"]},
  {title: '56', src: "/assets/gallery/56.jpg", tags: ["spaghetti", "food"]},
  {title: '57', src: "/assets/gallery/57.jpg", tags: ["food", "soup"]},
  {title: '58', src: "/assets/gallery/58.jpg", tags: ["spices", "food"]},
  {title: '59', src: "/assets/gallery/59.jpg", tags: ["burn", "file", "house", "matches"]},
  {title: '60', src: "/assets/gallery/60.jpg", tags: ["green", "spices"]},

  // next 5 photos for basics
  {title: '61', src: "/assets/design-images/outside-2.jpg", tags: [""]},
  {title: '62', src: "/assets/design-images/car-1.jpg", tags: [""]},
  {title: '63', src: "/assets/design-images/dinner-1.jpg", tags: [""]},
  {title: '64', src: "/assets/design-images/travel-1.jpg", tags: [""]},
  {title: '65', src: "/assets/design-images/nature-2.jpg", tags: [""]},
  {title: '65', src: "/assets/design-images/nature-3.jpg", tags: [""]},

  // next 5 photos for routing
  {title: '61', src: "/assets/design-images/nature-1.jpg", tags: [""]},
  {title: '62', src: "/assets/design-images/people-2.jpg", tags: [""]},
  {title: '63', src: "/assets/design-images/dinner-3.jpg", tags: [""]},
  {title: '64', src: "/assets/design-images/space-1.jpg", tags: [""]},
  {title: '65', src: "/assets/design-images/outside-1.jpg", tags: [""]},

  // resources
  {title: 'angular', src: "/assets/angular.svg", tags: [""]},
  {title: 'angular', src: "/assets/angular-focus.png", tags: [""]},
  {title: 'matias', src: "/assets/matias.jpg", tags: [""]},
  {title: 'matias', src: "/assets/matias-sky.jpg", tags: [""]},
  {title: 'lukas', src: "/assets/lukas.jpg", tags: [""]},
  {title: 'lukas', src: "/assets/lukas-sky.jpg", tags: [""]},
];
